name: Build and Deploy Expo App

on:
  push:
    branches:
      - main # prod
      - dev # dev

jobs:
  build:
    name: Build and Submit Expo App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
          check-latest: false

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli eas-cli
      
      - name: EAS Build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            eas build --platform android --profile production --non-interactive
          else
            eas build --platform android --profile development --non-interactive
          fi
      
      - name: Submit to Google Play Store
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          eas submit --platform android \
          --latest \
          --profile development \
          --non-interactive \
          --key "$GOOGLE_SERVICE_ACCOUNT_KEY"