name: Build and Deploy Expo App

on:
  push:
    branches:
      - main # prod
      - dev # dev

jobs:
  build:
    name: Build and Submit Expo App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
          check-latest: false

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli eas-cli
      
      # Install jq
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: EAS Build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            # Build for production profile on main branch
            eas build --platform android --profile production --non-interactive
            BUILD_URL=$(eas build:list --status finished --platform android --limit 1 --json | jq -r '.[0].artifacts.buildUrl')
          else
            # Build for development profile on dev branch
            eas build --platform android --profile development --non-interactive
            BUILD_URL=$(eas build:list --status finished --platform android --limit 1 --json | jq -r '.[0].artifacts.buildUrl')
          fi
        # Make the BUILD_URL available to later steps
        shell: bash

      - name: EAS Submit
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            eas submit --platform android --url $BUILD_URL --profile production --non-interactive
          else
            eas submit --platform android --url $BUILD_URL --profile development --non-interactive
          fi
